spring.application.name=veebipood

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.datasource.url=jdbc:postgresql://dpg-d7gt6dmgvqtc73epbcug-a.virginia-postgres.render.com/veebipood_database_jc58
spring.datasource.username=veebipood_user
spring.datasource.password=JMxAqH0Ohgef8NQ7EQJLy9Uhx0kQQN7c

#veebipood_user
#JMxAqH0Ohgef8NQ7EQJLy9Uhx0kQQN7c
#postgresql://veebipood_user:JMxAqH0Ohgef8NQ7EQJLy9Uhx0kQQN7c@dpg-d7gt6dmgvqtc73epbcug-a.virginia-postgres.render.com/veebipood_database_jc58